/* Interaction lab: every experiment that can be switched on with ?fx=<id>.
   Shared by interactions.html (the index) and fx.js (the badge on the home page). */
window.FX_LIST = [
  { id: 'pin-header', group: 'Scroll',
    name: 'Pinned header (your Figma)',
    desc: 'Figma 326:17182. The grid scrolls up until two rows are left, then pins with your name, role and links folded into one line. Click the name to go back to the top.',
    look: 'Scroll down past the grid.' },
  { id: 'sticky-hero', group: 'Scroll',
    name: 'Sticky name, full size',
    desc: 'The dot grid scrolls away; your name, links and role pin to the top so the projects take focus.',
    look: 'Scroll down past the grid.' },
  { id: 'compact-header', group: 'Scroll',
    name: 'Condensing header',
    desc: 'Like the full-size sticky name, but once pinned the name shrinks and the role line folds away.',
    look: 'Scroll down past the grid.' },
  { id: 'compact-inline', group: 'Scroll',
    name: 'Condensing header, role beside name',
    desc: 'The grid scrolls away and the header pins as one line: your name at 20px with Interaction, Digital Product Designer tucked in beside it, links on the right. Click the name to go back to the top.',
    look: 'Scroll down past the grid.' },
  { id: 'dots-dissolve', group: 'Scroll',
    name: 'Dots dissolve',
    desc: 'Each row of the grid shrinks to nothing as it reaches the top of the screen, instead of just sliding off.',
    look: 'Scroll slowly from the top.' },
  { id: 'rows-on-scroll', group: 'Scroll',
    name: 'Rows rise into view',
    desc: 'Tabs and project rows fade up one by one as they scroll into view.',
    look: 'Reload on a short window and scroll to the projects.' },
  { id: 'scroll-paint', group: 'Scroll',
    name: 'Scroll paints the grid',
    desc: 'Scrolling flicks random dots into post-it colours; the faster you scroll, the more light up. Pairs well with the pinned header.',
    look: 'Scroll quickly near the top.' },
  { id: 'footer-autohide', group: 'Scroll',
    name: 'Footer tucks away',
    desc: 'The pinned footer slides out of the way while you scroll down and comes back as soon as you scroll up.',
    look: 'Scroll down, then up a little.' },

  { id: 'dots-wave', group: 'Arrival',
    name: 'Dot ripple',
    desc: 'On load the grid pops in as a ripple spreading out from the theme toggle in the corner.',
    look: 'Reload the page.' },
  { id: 'bio-stagger', group: 'Arrival',
    name: 'Text rises in',
    desc: 'Role, bio paragraphs and the project list fade up one after another while the name types.',
    look: 'Reload the page.' },
  { id: 'intro-sequence', group: 'Arrival',
    name: 'Intro sequence',
    desc: 'A choreographed arrival: the dot grid ripples in from the toggle, then your name rises and types itself, then the links, role, bio and footer fade up in turn (projects follow if Rows rise into view is on). Any scroll, click or key skips it.',
    look: 'Reload the page; try it with Rows rise into view.' },
  { id: 'name-rise', group: 'Arrival',
    name: 'Name rises in',
    desc: 'Only your name fades up into place on load, while it types itself out. Everything else is still.',
    look: 'Reload the page.' },
  { id: 'role-typing', group: 'Arrival',
    name: 'Role types too',
    desc: 'After your name finishes typing, the role line types itself out in the same rhythm.',
    look: 'Reload the page.' },

  { id: 'focus-dim', group: 'Projects',
    name: 'Projects in focus',
    desc: 'While the pointer is on the work list, everything above it dims so only the projects are in focus.',
    look: 'Hover the work list.' },
  { id: 'row-nudge', group: 'Projects',
    name: 'Row nudge',
    desc: 'The hovered project slides right a touch and an arrow appears before it.',
    look: 'Hover any project.' },
  { id: 'title-scramble', group: 'Projects',
    name: 'Title decode',
    desc: 'Project titles scramble through glyphs and settle back into their name, which suits the monospace type.',
    look: 'Hover any project.' },
  { id: 'stat-countup', group: 'Projects',
    name: 'Number counts up',
    desc: 'When a summary opens, its figure counts up: 0% to 90% for CDC.',
    look: 'Hover CDC w Xendit.' },
  { id: 'row-rule', group: 'Projects',
    name: 'Rule draws under row',
    desc: 'A hairline draws across beneath the hovered project, like a ruler.',
    look: 'Hover any project.' },
  { id: 'wip-note', group: 'Projects',
    name: 'WIP explains itself',
    desc: 'The WIP badge gives a small wiggle when it appears and a note reads \u201ccase study in progress\u201d.',
    look: 'Hover Bulk download, Learn, Save plus or Teenage Banking.' },
  { id: 'key-nav', group: 'Projects',
    name: 'Keyboard browsing',
    desc: 'Arrow keys (or J / K) step through the projects with the hover state and image; Enter opens a case study, Esc clears.',
    look: 'Press \u2193 a few times.' },
  { id: 'tab-slider', group: 'Projects',
    name: 'Sliding tab',
    desc: 'The post-it highlight slides between tabs and the new list cascades in row by row.',
    look: 'Switch between work, lab, experiments, featured.' },

  { id: 'preview-wipe', group: 'Images',
    name: 'Image wipe',
    desc: 'Previews reveal top to bottom like a blind instead of fading.',
    look: 'Hover a project with an image (window 1390px or wider).' },
  { id: 'preview-zoom', group: 'Images',
    name: 'Image focus pull',
    desc: 'Previews arrive slightly small and soft, then settle into full size and sharp.',
    look: 'Hover a project with an image.' },
  { id: 'preview-follow', group: 'Images',
    name: 'Image follows cursor',
    desc: 'The preview drifts up and down with your pointer, eased, instead of snapping to the row.',
    look: 'Move slowly down the work list.' },
  { id: 'preview-tilt', group: 'Images',
    name: 'Image tilt',
    desc: 'The preview tilts gently in 3D toward the pointer, like picking up a card.',
    look: 'Move across a project row.' },

  { id: 'pixel-reveal', group: 'Images',
    name: 'Pixel reveal',
    desc: 'Previews dissolve in through a grid of squares, echoing the dot grid.',
    look: 'Hover a project with an image.' },

  { id: 'cursor-square', group: 'Details',
    name: 'Square cursor companion',
    desc: 'A small post-it square trails the pointer and grows over anything clickable.',
    look: 'Move the pointer around, over links and projects.' },
  { id: 'page-fade', group: 'Details',
    name: 'Page fades between pages',
    desc: 'The page fades in on arrival and lifts away before going to the case study or photography.',
    look: 'Click CDC w Xendit or Photography, then go back.' },
  { id: 'dots-proximity', group: 'Details',
    name: 'Dot lens',
    desc: 'Dots near the pointer shrink away from it, a soft dent that follows you across the grid.',
    look: 'Move the pointer over the grid.' },
  { id: 'underline-draw', group: 'Details',
    name: 'Drawn underlines',
    desc: 'On hover a link’s underline retracts and draws back in from the left.',
    look: 'Hover LinkedIn, CIID, About, Photography.' },
  { id: 'magnetic-links', group: 'Details',
    name: 'Magnetic links',
    desc: 'LinkedIn, Email and Resume lean a few pixels toward the pointer as it comes near.',
    look: 'Move near the contact links.' },
  { id: 'theme-circle', group: 'Details',
    name: 'Theme ripple',
    desc: 'Switching theme spreads the new one out in a circle from the toggle (Chrome, Edge, Safari 18+).',
    look: 'Click the round toggle at the end of the grid.' }
];

/* Lab for the CDC w Xendit case study: cdc-w-xendit.html?fx=<id> */
window.CASE_FX_LIST = [
  { id: 'toc-list', group: 'Section index',
    name: 'Side index',
    desc: 'The section names sit in a column to the left of the text; the one you are reading is highlighted. Click one to jump.',
    look: 'Scroll the page (window 1200px or wider).' },
  { id: 'toc-numbered', group: 'Section index',
    name: 'Numbered chapters',
    desc: 'Like the side index, but numbered 01 to 06, with a thin bar under the current chapter filling as you read through it.',
    look: 'Scroll the page (window 1200px or wider).' },
  { id: 'toc-ticks', group: 'Section index',
    name: 'Ticks that name themselves',
    desc: 'Only short ticks on the left, one per section. The current tick grows and its name slides out; hover any tick to read it.',
    look: 'Scroll, then hover the ticks.' },
  { id: 'toc-rail', group: 'Section index',
    name: 'Progress rail',
    desc: 'A vertical line fills as you read, with a mark for each section placed where it sits in the story.',
    look: 'Scroll the page (window 1200px or wider).' },
  { id: 'toc-crumb', group: 'Section index',
    name: 'Section in the back bar',
    desc: 'No side column: the top bar reads “back / Research” and changes as you move through the story. Works on phones too.',
    look: 'Scroll and watch the top bar.' },
  { id: 'toc-pill', group: 'Section index',
    name: 'Chapter pill',
    desc: 'A small pill at the bottom shows where you are (03/06 Decision); tap it to open the list of sections. Works on phones too.',
    look: 'Scroll, then click the pill.' },

  { id: 'read-progress', group: 'Reading',
    name: 'Reading progress',
    desc: 'A thin post-it line along the top fills as you read.',
    look: 'Scroll the page.' },
  { id: 'heading-sticky', group: 'Reading',
    name: 'Headings stay with you',
    desc: 'Each section heading sticks under the back bar while you read that section, then hands over to the next.',
    look: 'Scroll through a long section like Decision.' },
  { id: 'text-focus', group: 'Reading',
    name: 'Reading spotlight',
    desc: 'The paragraph in the middle of the screen is full strength; the ones above and below soften.',
    look: 'Scroll slowly through the text.' },
  { id: 'stat-marker', group: 'Reading',
    name: 'Numbers get marked',
    desc: 'Figures like 72-hour, 5,000 and 90% get a post-it marker swept under them as they come into view.',
    look: 'Scroll to Context and Research.' },

  { id: 'hero-parallax', group: 'Images',
    name: 'Hero settles away',
    desc: 'The cover image eases in scale and fades a little as you scroll past it.',
    look: 'Scroll from the very top.' },
  { id: 'img-reveal', group: 'Images',
    name: 'Images rise in',
    desc: 'Screens fade up into place as they scroll into view.',
    look: 'Scroll the page.' },
  { id: 'img-pixel', group: 'Images',
    name: 'Images dissolve in',
    desc: 'Screens appear through a grid of squares, echoing the dot grid on the home page.',
    look: 'Scroll the page.' },
  { id: 'img-lightbox', group: 'Images',
    name: 'Click to enlarge',
    desc: 'Click any image to see it full screen; click, scroll or press Esc to close. Useful for the dense screen boards.',
    look: 'Click the Research or Decision screens.' }
];
